apiVersion: apps/v1
kind: Deployment
medatada:
    name: microservice-libreria-deploy
    labels:
        name: microservice-libreria-deploy
        app: microservice
spec:
    replicas: 2
    selector:
        matchLabels:
            app: microservice-libreria
            type: microservice
    template:
        metadata:
            name: microservice-libreria-pod
            labels:
                app: microservice-libreria
                type: microservice
        spec:
            containers:
                - name: microservice-libreria-app
                  image: cursosbryan/serviciosapilibreria:latest
                  ports:
                    - containerPort: 80
                  env:
                    - name: MongoDb__ConnectionString
                      value: mongodb://cursosbryan:Pruebasdocker10@mongo-service:27017